Module4 task1
htmlacademy-javascript/1934365-keksobooking-26 pull request #3
Opened 2022-06-17 19:54 UTC by NatashaStr

2022-06-18 08:44 UTC, Manyaka requested changes

2022-06-18 08:44 UTC, Manyaka commented on js/main.js
> +  const maxRoomsValue = 6;
посмотри в критериях как надо писать константы

2022-06-18 08:44 UTC, Manyaka commented on js/main.js
> +  const maxRoomsValue = 6;
поправь везде по коду

2022-06-18 08:44 UTC, Manyaka commented on js/main.js
> +const TYPES = ['palace', 'flat', 'house', 'bungalow', 'hotel'];
также посмотри в критериях в каком месте должны располагаться константы

2022-06-20 04:50 UTC, Manyaka requested changes

2022-06-20 04:50 UTC, Manyaka commented on js/main.js
> +  const randomLng = getRandomPositiveFloat(139.7, 139.8);
35,65 - и другие - это магические числа

2022-06-20 04:50 UTC, Manyaka commented on js/main.js
> +// eslint-disable-next-line no-unused-vars
убери дисейбл еслинта, если не пользуешься переменной - то не пользуйся переменной

2022-06-20 04:50 UTC, Manyaka commented on js/main.js
> +createAd();
Зачем тут функцию вызываешь?

2022-06-20 04:50 UTC, Manyaka commented on js/main.js
> +      price: getRandomPositiveInteger(800, 20000),
магические числа

2022-06-20 04:50 UTC, Manyaka commented on js/main.js
> +  return Math.floor(Math.random() * Math.abs(MAX_ROOMS_VALUE));
что делает Math.abs?

2022-06-20 04:50 UTC, Manyaka commented on js/main.js
> +  for (let i = 1; i <= 10; i++) {
10 - это что?

2022-06-20 04:50 UTC, Manyaka commented on js/main.js
> +const SIMILAR_ADS_COUNT = 10;
отлично, все переменные правильно написала и все вынесла наверх файла - всё правильно сделала!

2022-06-20 11:02 UTC, NatashaStr commented on js/main.js
> +  const randomLng = getRandomPositiveFloat(139.7, 139.8);
исправлено

2022-06-20 11:07 UTC, NatashaStr commented on js/main.js
> +createAd();
исправлено (убрала вызов функции)

2022-06-20 11:09 UTC, NatashaStr commented on js/main.js
> +      price: getRandomPositiveInteger(800, 20000),
исправлено

2022-06-20 11:16 UTC, NatashaStr commented on js/main.js
> +  for (let i = 1; i <= 10; i++) {
исправлено

2022-06-20 11:17 UTC, NatashaStr commented on js/main.js
> +// eslint-disable-next-line no-unused-vars
исправлено

2022-06-20 12:10 UTC, NatashaStr commented on js/main.js
> +  return Math.floor(Math.random() * Math.abs(MAX_ROOMS_VALUE));
исправлено

2022-06-21 04:47 UTC, Manyaka requested changes

2022-06-21 04:47 UTC, Manyaka commented on js/main.js
> +const CHECKTIME = ['12:00', '13:00', '14:00'];
```suggestion
const CHECK_TIME = ['12:00', '13:00', '14:00'];
```

2022-06-21 04:47 UTC, Manyaka commented on js/main.js
> +const MAX_AVATAR_VALUE = 10;
нет, не так, подумай ещё, как связано у тебя число аватарок и количество рекламных объявлений?

2022-06-21 04:47 UTC, Manyaka commented on js/main.js
> +const getGuestsValue = function () {
как думаешь, есть ли в этих функциях что-то похожее?

2022-06-21 04:47 UTC, Manyaka commented on js/main.js
> +const getFeatures = function () {
аналогично: фичерез и фотос - похожи ли эти функции?

2022-06-21 04:49 UTC, Manyaka requested changes

2022-06-21 04:49 UTC, Manyaka commented on js/main.js
> +      adress: `${randomLat  }, ${  randomLng}`,
```suggestion
      address: `${randomLat  }, ${  randomLng}`,
```

2022-06-22 05:52 UTC, Manyaka requested changes

2022-06-22 05:52 UTC, Manyaka commented on js/main.js
> +  const lengthOfNewArray = getRandomPositiveInteger(1, maxLength);
пусть эта функция честно подсмотрена, но как ты думаешь, возможна такая ситуация, когда не будет фич или фоток?

2022-06-22 05:52 UTC, Manyaka commented on js/main.js
> +const generateAvatar = createRandomAvatar(1, SIMILAR_ADS_COUNT);
как думаешь, можно ли обойтись без этой прокладочной переменной? которую ты почему то в ключе аватар вызываешь как функцию, тогда как это у тебя переменная.

2022-06-22 05:52 UTC, Manyaka commented on js/main.js
> +  return function () {
интересно, ты понимаешь что ты тут делаешь? Просто в js есть концепция - first-class citizens function, можешь почитать в гугле, если интересно. Но я не думаю, что ты на этом уровне познания в js, что намеренно возвращаешь функцию. Так что перепиши это. Если не знаешь как, можем созвониться и обсудить.

2022-06-24 04:13 UTC, Manyaka requested changes

2022-06-24 04:13 UTC, Manyaka commented on js/main.js
> +      address: `${randomLat, randomLng}`,
```suggestion
      address: `${randomLat}, ${randomLng}`,
```

2022-06-24 05:30 UTC, merged