Отрисуй меня полностью (часть 1)
htmlacademy-javascript/1934365-keksobooking-26 pull request #5
Opened 2022-06-30 13:49 UTC by NatashaStr

---
:mortar_board: [Отрисуй меня полностью (часть 1)](https://up.htmlacademy.ru/javascript/26/user/1934365/tasks/12)

2022-06-30 13:55 UTC, Manyaka requested changes

2022-06-30 13:55 UTC, Manyaka commented on js/cards.js
> +// const offerNameByType = {
название неудачное, не отражает то, что в словаре, это же не словарь имён

2022-06-30 13:55 UTC, Manyaka commented on js/cards.js
> +const cardPlaceElement = cardPlace.querySelector('.map__canvas');
> , в блок #map-canvas, 

в тз блок другой

2022-07-04 05:21 UTC, Manyaka requested changes

2022-07-04 05:21 UTC, Manyaka commented on js/cards.js
> +const cardTemplate = document.querySelector('#card').content.querySelector('.popup'); //Находим в содержимом шаблона блок с классом popup
```suggestion
// Находим в содержимом шаблона блок с классом popup
const cardTemplate = document.querySelector('#card').content.querySelector('.popup'); 
```

2022-07-04 05:21 UTC, Manyaka commented on js/cards.js
> +const cardTemplate = document.querySelector('#card').content.querySelector('.popup'); //Находим в содержимом шаблона блок с классом popup
коменты писать можно, я вообще очень даже их приветствую

2022-07-04 05:21 UTC, Manyaka commented on js/cards.js
> +const accomodationType = {// Словарь видов жилья
```suggestion
const accommodationType = {// Словарь видов жилья
```

2022-07-04 05:21 UTC, Manyaka commented on js/cards.js
> +const similarAdds = createAdds();//Присваиваем переменной значение функции по созданию массива с объектами
соотв, какое тут значение будет? - это я твои коменты читаю и спрашиваю, для уточнения :)

2022-07-04 05:21 UTC, Manyaka commented on js/cards.js
> +  featureListTemplateElement.forEach((listItem) => {//Для каждого элемента списка проводим сл.операцию
отдей пустой строкой - начался другой блок кода, оптимальнее это показывать, так и читать легче

2022-07-04 05:21 UTC, Manyaka commented on js/cards.js
> +    if (makeFeatureArray.includes(cssModifier)) {//Если в модифицированном массиве есть модификатор, то
здесь тоже - начался блок кода - значит отбиваем пустой строкой вверху

2022-07-04 05:21 UTC, Manyaka commented on js/data.js
> +  for (let i = 1; i <= SIMILAR_ADS_COUNT; i++) {
:) так нельзя, `i` идет всегда с `0` и до бесконечности, это закрепленное, а главное, ожидаемое поведение `i`, и все программисты его ожидают.
Что тебе тут надо сделать?

2022-07-04 10:22 UTC, NatashaStr commented on js/cards.js
> +const similarAdds = createAdds();//Присваиваем переменной значение функции по созданию массива с объектами
здесь будет массив, в котором будут объекты (объявления)

2022-07-04 15:07 UTC, Manyaka requested changes

2022-07-04 15:07 UTC, Manyaka commented on js/cards.js
> +  for (let i = 0; i < photoArray.length; i++) {
начался блок кода. Отбивает пустой строкой. Кстати, видимо пора тебя уже спросить - что такое блок кода? Как понять, что начался блок кода?

2022-07-04 15:07 UTC, Manyaka commented on js/cards.js
> +similarAdds.forEach((card) => {
вот отсюда у тебя началась одна функция - фор-ич пока так её обзовём, внутри кроме одно действия - заполнения карточки инфой, появляются ещё действия. Функция разрастается, ей неудобно манипулировать.
 Чтобы этого избежать - надо другие действия вынести в свои маленькие функции.

2022-07-04 18:26 UTC, NatashaStr commented on js/cards.js
> +  for (let i = 0; i < photoArray.length; i++) {
Я думаю, что блок кода это набор инструкций, объединенных какой-то логикой.  Вот только на скрине, который ты прислала, для меня вся эта функция это блок. Или строка, которая создает фрагмент тоже может быть отдельным блоком?

2022-07-04 18:41 UTC, Manyaka commented on js/cards.js
> +  for (let i = 0; i < photoArray.length; i++) {
нет, у блока кода в js есть чёткое определение. Поищи ещё :)

2022-07-07 04:30 UTC, Manyaka requested changes

2022-07-07 04:30 UTC, Manyaka commented on js/cards.js
> +const createAccommodationType = (accommodationName, addTemplateElement) => {
```suggestion
const getAccommodationType = (type, element) => {
```

`get` - получить. Нам надо _получить_ тип жилья, а не создать тип жилья, потому что _создание_ - это что-то новое, а нам надо из уже существующих типов получить нужный нам. Поэтому get

2022-07-08 05:47 UTC, merged